kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appprod-pull-from-appdev
  namespace: appdev
subjects:
  - kind: ServiceAccount
    name: default
    namespace: appprod
  - kind: ServiceAccount
    name: pipeline
    namespace: appprod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'