apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: testflask-pipelinerun-
  namespace: 1234-tekton
  labels:
    tekton.dev/pipeline: testflask-pipeline
spec:
  pipelineRef:
    name: testflask-pipeline
  resources:
    - name: testflask-git
      resourceRef:
        name: git-testflask
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: local-repo
      persistentVolumeClaim:
        claimName: tekton-repo
