apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-${APP_NAME}
  namespace: ${TEKTON_NAMESPACE}
spec:
  params:
    - name: url
      value: 'https://github.com/MoOyeg/testFlask.git'
    - name: revision
      value: master
  type: git
