apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: message-binding
  namespace: ${TEKTON_NAMESPACE}
spec:
  params:
    - name: message
      value: Hello from the Triggers EventListener!
