kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${TEKTON_PVC_NAME}
  namespace: ${TEKTON_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
