apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-${APP_NAME}
  namespace: ${TEKTON_NAMESPACE}
spec:
  params:
    - name: url
      value: ${CODE_URL}
    - name: revision
      value: master
  type: git
