apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: testflask-pipelinerun
  labels:
    tekton.dev/pipeline: testflask-pipeline
spec:
  params:
    - name: APP_IMAGE_URL
      value: appdev/testflask
    - name: APP_CONFIG
      value: gunicorn.conf.py
    - name: APP_NAME
      value: testflask
    - name: APP_MODULE
      value: testapp:app
    - name: MYSQL_DATABASE
      value: testdb
    - name: SECRET_NAME
      value: my-secret
    - name: MYSQL_HOST
      value: mysql
    - name: NAMESPACE_DEV
      value: appdev
    - name: NAMESPACE_PROD
      value: appprod
  pipelineRef:
    name: testflask-pipeline
  resources:
    - name: test-git
      resourceRef:
        name: git-testflask
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: testflask-cicd-pvc
      persistentVolumeClaim:
        claimName: testflask-cicd-pvc
