apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appprod
patchesStrategicMerge:
  - patch-is.yaml
commonLabels:
  deploy-env: prod
  editor: kustomize
bases:
  - ../../base
resources:
  - namespace.yaml
  - prod-rolebinding.yaml
