apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appprod
#Feature got broken in new kustomize https://github.com/kubernetes-sigs/kustomize/issues/641
#patchesStrategicMerge:
#  - ./patches/patch-is.yaml
commonLabels:
  deploy-env: prod
  editor: kustomize
bases:
  - ../../base
  - ../../base-secret
resources:
  - namespace.yaml
  - prod-rolebinding.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - mysql-imagestream.yaml
