apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appprod
patchesStrategicMerge:
  - ./patches/patch-is.yaml
commonLabels:
  deploy-env: prod
  editor: kustomize
bases:
  - ../../base
resources:
  - namespace.yaml
  - prod-rolebinding.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - mysql-imagestream.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: my-secret
    literals:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
