kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: mysql
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 8.0-el8
      annotations: null
      from:
        kind: DockerImage
        name: >-
          image-registry.openshift-image-registry.svc:5000/openshift/mysql:8.0-el8
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Source
status:
  dockerImageRepository: "image-registry.openshift-image-registry.svc:5000/appprod/mysql"
