kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appdev-rolebinding
  namespace: appdev
  labels:
    deploy-env: dev
    editor: kustomize
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: 1234-tekton
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
