apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: testflask-pipelinerun
  generateName: testflask-pipelinerun-
  labels:
    tekton.dev/pipeline: testflask-pipeline
spec:
  #Creating PipelineRun as Pending
  status: "PipelineRunPending"
  params:
    - name: APP_CONFIG
      value: gunicorn.conf.py
    - name: APP_NAME
      value: testflask
    - name: APP_MODULE
      value: testapp:app
    - name: MYSQL_DATABASE
      value: testdb
    - name: SECRET_NAME
      value: my-secret
    - name: MYSQL_HOST
      value: mysql
    - name: NAMESPACE_DEV
      value: appdev
    - name: NAMESPACE_PROD
      value: appprod
    - name: GIT_URL
      value: https://github.com/MoOyeg/testFlask.git
    - name: GIT_BRANCH
      value: master
    - name: PYTHON_VERSION
      value: 3.6.15
    - name: OUTPUT_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/appdev/testflask
  pipelineRef:
    name: testflask-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  # workspaces:
  #   - name: testflask-cicd-pvc
  #     persistentVolumeClaim:
  #       claimName: testflask-cicd-pvc
  workspaces:
    - name: testflask-cicd-pvc
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
